### ISSUE TITLE
Can any one provide a script for sft?

### ISSUE THREAD

**Issue by zlh1992** [GreenBitAI/low_bit_llama#1]
The  script of sft_alpaca is just the same as inferenece.py

**Comment by NicoNico6** [comment]
Both the evaluations for the alpaca finetuned LLM and the pre-trained LLM are accessible. The primary distinction lies in the loading of the Lora adapter parameters. Kindly refer to the following links to understand the differences:

[llama_2b_inference.py L20](https://github.com/GreenBitAI/low_bit_llama/blob/12052be489e77b515d6cdf1d89b477b0bbf75fa3/llama_2b_inference.py#L20)

[llama_2b_sft_alpaca.py L31](https://github.com/GreenBitAI/low_bit_llama/blob/12052be489e77b515d6cdf1d89b477b0bbf75fa3/llama_2b_sft_alpaca.py#L31)
